name: Microsite

on:
  pull_request:
    branches: [docs]
  push:
    branches: [docs]

jobs:
  build:
    name: Generate Microsite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: 'website/yarn.lock'

      - name: Build
        run: ./build.sh

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/cats-effect
          publish_branch: gh-pages
